Repository SpongePowered/Ore, pull requests merged in 2018-08, with the labels that each got.

#603 Show Flags unread notification
  app/models/viewhelper/HeaderData.scala
Labels: component: frontend

#605 Move hidden projects to secured category on discourse
  app/controllers/project/Projects.scala
  app/discourse/OreDiscourseApi.scala
  app/discourse/SpongeForums.scala
  build.sbt
  conf/application.conf.template
Labels: component: discourse, requires: config update, requires: environment update, requires: forums update, status: ready for review

#609 Show message when PGP key is successfully uploaded
  app/views/users/view.scala.html
Labels: component: frontend

#614 Fix Soft Delete Visibility Logging
  app/controllers/project/Projects.scala
Labels: component: backend

#641 More filters and action contexts
  app/assets/stylesheets/main.scss
  app/controllers/Application.scala
  app/db/impl/schema.scala
  app/models/admin/LoggedActionView.scala
  app/models/user/LoggedAction.scala
  app/views/bootstrap/header.scala.html
  app/views/projects/versions/view.scala.html
  app/views/projects/view.scala.html
  app/views/users/admin/log.scala.html
  conf/evolutions/default/98.sql
  conf/routes
Labels: status: ready for review

#645 add skip review button for a version
  app/controllers/Application.scala
  app/controllers/Reviews.scala
  app/db/impl/schema.scala
  app/db/impl/table/ModelKeys.scala
  app/models/project/Version.scala
  app/models/user/LoggedAction.scala
  app/views/users/admin/reviews.scala.html
  conf/evolutions/default/99.sql
  conf/routes
  public/javascripts/review.js
Labels: status: ready for review

#646 Rewrite Metadata Ripper to support multiple types of files, and add Mixin Tag
  app/controllers/project/Projects.scala
  app/controllers/project/Versions.scala
  app/models/project/Tag.scala
  app/models/project/Version.scala
  app/ore/project/factory/PendingProject.scala
  app/ore/project/factory/ProjectFactory.scala
  app/ore/project/io/PluginFile.scala
  app/ore/project/io/PluginFileData.scala
Labels: status: ready to merge

#644 Platform Tags
  OreTestPlugin/build.gradle
  app/controllers/Application.scala
  app/controllers/project/Projects.scala
  app/controllers/project/Versions.scala
  app/controllers/sugar/Calls.scala
  app/models/project/Project.scala
  app/models/project/Tag.scala
  app/models/project/Version.scala
  app/models/viewhelper/VersionData.scala
  app/ore/Platforms.scala
  app/ore/project/Dependency.scala
  app/ore/project/factory/PendingProject.scala
  app/ore/project/factory/PendingVersion.scala
  app/ore/project/factory/ProjectFactory.scala
  app/ore/project/io/PluginFile.scala
  app/ore/project/io/PluginFileData.scala
  app/views/bootstrap/header.scala.html
  app/views/home.scala.html
  app/views/projects/channels/helper/modalManage.scala.html
  app/views/projects/list.scala.html
  app/views/projects/tag.scala.html
  app/views/projects/versions/list.scala.html
  app/views/projects/versions/view.scala.html
  conf/routes
Labels: status: ready to merge

#655 Fixes subpage access
  app/controllers/project/Pages.scala
Labels: component: backend, priority: high, status: ready for review
