Repository SpongePowered/Ore, pull requests merged in 2018-07, with the labels that each got.

#490 Log User Actions (#392)
  app/controllers/Application.scala
  app/controllers/OreBaseController.scala
  app/controllers/project/Pages.scala
  app/controllers/project/Projects.scala
  app/controllers/project/Versions.scala
  app/db/impl/OrePostgresDriver.scala
  app/db/impl/schema.scala
  app/db/impl/service/OreModelConfig.scala
  app/db/impl/service/OreModelService.scala
  app/models/user/LoggedAction.scala
  app/ore/permission/Permission.scala
  app/ore/permission/PermissionPredicate.scala
  app/security/NonceFilter.scala
  app/views/bootstrap/header.scala.html
  app/views/projects/discuss.scala.html
  app/views/users/admin/log.scala.html
  build.sbt
  conf/evolutions/default/93.sql
  conf/messages
  conf/routes
Labels: priority: high, status: in progress

#571 Only allow staff to access Staff page
  app/controllers/Users.scala
Labels: status: ready for review

#569 Don't show versions in queue from deleted projects
  app/controllers/Application.scala
Labels: status: ready for review

#574 Add rel="noopener" when using target="_blank"
  app/views/bootstrap/footer.scala.html
  app/views/errors/error.scala.html
  app/views/projects/discuss.scala.html
  app/views/projects/pages/view.scala.html
  app/views/projects/view.scala.html
  app/views/users/admin/flags.scala.html
  app/views/users/invite/form.scala.html
  public/errors/400.html
  public/errors/404.html
  public/errors/500.html
  public/errors/502.html
Labels: status: ready for review

#570 Explain in the delete modal that we reserve the unique id
  app/views/projects/settings.scala.html
  conf/messages
Labels: status: ready for review

#573 Show role white highest trust on authors & staff page
  app/views/users/authors.scala.html
  app/views/users/staff.scala.html
Labels: status: ready for review

#575 Reorganizing Permissions for Moderators
  app/controllers/project/Versions.scala
  app/models/viewhelper/ScopedProjectData.scala
  app/ore/permission/Permission.scala
  app/ore/permission/role/RoleTypes.scala
  app/ore/permission/role/Trust.scala
  app/views/projects/versions/list.scala.html
  app/views/projects/versions/view.scala.html
Labels: component: backend, status: input wanted

#577 add dropdown on download btn for Copy URL
  app/models/viewhelper/ProjectData.scala
  app/views/bootstrap/layout.scala.html
  app/views/projects/versions/view.scala.html
  app/views/projects/view.scala.html
  build.sbt
  public/javascripts/main.js
Labels: status: ready for review

#581 Maybe fix project creation error
  app/models/project/Project.scala
  app/ore/project/factory/PendingProject.scala
Labels: component: backend

#530 Add version visibilities resolves #479
  app/controllers/ApiController.scala
  app/controllers/OreBaseController.scala
  app/controllers/project/Versions.scala
  app/db/access/ModelAccess.scala
  app/db/impl/access/ProjectBase.scala
  app/db/impl/model/common/Hideable.scala
  app/db/impl/model/common/VisibilityChange.scala
  app/db/impl/schema.scala
  app/db/impl/service/OreModelConfig.scala
  app/db/impl/service/OreModelService.scala
  app/db/impl/table/ModelKeys.scala
  app/db/impl/table/common/VisibilityChangeColumns.scala
  app/models/admin/ProjectVisibilityChange.scala
  app/models/admin/VersionVisibilityChange.scala
  app/models/project/Project.scala
  app/models/project/Version.scala
  app/models/viewhelper/HeaderData.scala
  app/models/viewhelper/ProjectData.scala
  app/ore/permission/Permission.scala
  app/ore/rest/OreRestfulApi.scala
  app/views/projects/channels/list.scala.html
  app/views/projects/log.scala.html
  app/views/projects/versions/list.scala.html
  app/views/projects/versions/log.scala.html
  app/views/projects/versions/view.scala.html
  app/views/projects/view.scala.html
  app/views/users/admin/visibility.scala.html
  conf/evolutions/default/94.sql
  conf/messages
  conf/routes
  public/javascripts/versionList.js
Labels: component: backend, status: ready for review

#546 Make Ore localizable
  app/controllers/ApiController.scala
  app/controllers/OreBaseController.scala
  app/controllers/Organizations.scala
  app/controllers/Reviews.scala
  app/controllers/Users.scala
  app/controllers/project/Projects.scala
  app/controllers/project/Versions.scala
  app/controllers/sugar/Actions.scala
  app/db/impl/OrePostgresDriver.scala
  app/db/impl/access/OrganizationBase.scala
  app/db/impl/schema.scala
  app/db/impl/table/ModelKeys.scala
  app/form/organization/OrganizationMembersUpdate.scala
  app/mail/EmailFactory.scala
  app/models/admin/Review.scala
  app/models/project/Project.scala
  app/models/project/ProjectSettings.scala
  app/models/user/Notification.scala
  app/models/user/User.scala
  app/ore/project/NotifyWatchersTask.scala
  app/ore/project/factory/ProjectFactory.scala
  app/ore/project/io/PluginFile.scala
  app/security/spauth/SingleSignOnConsumer.scala
  app/security/spauth/SpongeAuthApi.scala
  app/security/spauth/SpongeUser.scala
  app/util/StringUtils.scala
  app/views/users/notifications.scala.html
  conf/application.conf.template
  conf/evolutions/default/95.sql
Labels: status: ready for review

#592 Remove ¶ char in diff & fix ProjectMemberRemoved
  app/controllers/project/Projects.scala
  public/javascripts/actionLog.js
Labels: status: ready for review
