Repository SpongePowered/Ore, pull requests merged in 2018-09, with the labels that each got.

#586 Hydra Sponsorship
  .gitignore
  README.md
  conf/application.conf.template
  public/images/sponsors/triplequote_black.svg
  public/images/sponsors/triplequote_white.svg
Labels: requires: config update, status: ready to merge

#663 Apply roles on login
  app/models/user/User.scala
  app/security/spauth/SingleSignOnConsumer.scala
  app/security/spauth/SpongeAuthApi.scala
  app/security/spauth/SpongeUser.scala
Labels: status: ready for review

#660 Use internal names instead of the forum role id
  app/controllers/ApiController.scala
  app/controllers/Application.scala
  app/controllers/Reviews.scala
  app/db/impl/OrePostgresDriver.scala
  app/db/impl/access/OrganizationBase.scala
  app/db/impl/access/UserBase.scala
  app/db/impl/schema.scala
  app/db/impl/table/ModelKeys.scala
  app/form/RoleSetBuilder.scala
  app/form/organization/OrganizationMembersUpdate.scala
  app/form/organization/TOrganizationRoleSetBuilder.scala
  app/form/project/TProjectRoleSetBuilder.scala
  app/models/project/Project.scala
  app/models/project/ProjectSettings.scala
  app/models/user/Organization.scala
  app/models/user/User.scala
  app/models/user/role/OrganizationRole.scala
  app/models/user/role/ProjectRole.scala
  app/models/user/role/RoleModel.scala
  app/ore/permission/PermissionPredicate.scala
  app/ore/permission/role/GlobalRole.scala
  app/ore/permission/role/Role.scala
  app/ore/permission/role/RoleTypes.scala
  app/ore/project/factory/ProjectFactory.scala
  app/ore/rest/OreRestfulApi.scala
  app/ore/user/FakeUser.scala
  app/views/users/admin/userAdmin.scala.html
  app/views/users/invite/roleSelect.scala.html
  app/views/users/projects.scala.html
  build.sbt
  conf/evolutions/default/101.sql
Labels: status: ready for review

#662 Allow multiple downloads at the same time
  app/controllers/project/Versions.scala
  app/models/project/DownloadWarning.scala
  conf/evolutions/default/102.sql
Labels: status: ready for review

#664 Improve performance in general, and especially on homepage
  app/controllers/Application.scala
  app/controllers/project/Pages.scala
  app/db/impl/access/ProjectBase.scala
  app/db/impl/access/UserBase.scala
  app/models/project/Project.scala
  app/models/user/Organization.scala
  app/models/user/User.scala
  app/models/viewhelper/HeaderData.scala
  app/ore/permission/PermissionPredicate.scala
  app/ore/permission/scope/OrganizationScope.scala
  app/ore/permission/scope/ProjectScope.scala
  app/ore/permission/scope/Scope.scala
  conf/evolutions/default/104.sql
Labels: component: backend, component: permissions, status: ready for review, type: enhancement

#668 Add addition Sentry data
  app/controllers/sugar/Actions.scala
  app/models/viewhelper/HeaderData.scala
Labels: status: ready for review
