Repository SpongePowered/Ore, pull requests merged in 2018-11, with the labels that each got.

#701 Added intellij code style
  CONTRIBUTING.md
  extra/ore-intellij-style.xml
Labels: status: ready for review

#691 Added asset versioning
  app/views/bootstrap/footer.scala.html
  app/views/bootstrap/layout.scala.html
  app/views/createOrganization.scala.html
  app/views/errors/error.scala.html
  app/views/errors/notFound.scala.html
  app/views/errors/timeout.scala.html
  app/views/home.scala.html
  app/views/projects/admin/notes.scala.html
  app/views/projects/channels/list.scala.html
  app/views/projects/create.scala.html
  app/views/projects/discuss.scala.html
  app/views/projects/helper/inputSettings.scala.html
  app/views/projects/pages/modalPageCreate.scala.html
  app/views/projects/pages/view.scala.html
  app/views/projects/settings.scala.html
  app/views/projects/versions/create.scala.html
  app/views/projects/versions/list.scala.html
  app/views/projects/view.scala.html
  app/views/users/admin/flags.scala.html
  app/views/users/admin/log.scala.html
  app/views/users/admin/queue.scala.html
  app/views/users/admin/reviews.scala.html
  app/views/users/admin/stats.scala.html
  app/views/users/admin/userAdmin.scala.html
  app/views/users/admin/visibility.scala.html
  app/views/users/authors.scala.html
  app/views/users/invite/form.scala.html
  app/views/users/memberList.scala.html
  app/views/users/notifications.scala.html
  app/views/users/projects.scala.html
  app/views/users/staff.scala.html
  app/views/users/view.scala.html
  build.sbt
  conf/routes
  project/plugins.sbt
Labels: status: ready for review

#700 Fix last updated for new versions
  app/controllers/ApiController.scala
  app/controllers/project/Versions.scala
Labels: status: ready for review

#704 More typeclasses (UserOwned, ProjectOwned, OrganizationOwned)
  app/controllers/ApiController.scala
  app/controllers/Application.scala
  app/controllers/Organizations.scala
  app/controllers/Reviews.scala
  app/controllers/project/Projects.scala
  app/controllers/project/Versions.scala
  app/db/impl/access/OrganizationBase.scala
  app/db/impl/access/ProjectBase.scala
  app/discourse/OreDiscourseApi.scala
  app/form/organization/OrganizationMembersUpdate.scala
  app/models/admin/LoggedActionView.scala
  app/models/admin/ProjectLog.scala
  app/models/api/ProjectApiKey.scala
  app/models/project/Channel.scala
  app/models/project/Flag.scala
  app/models/project/Page.scala
  app/models/project/Project.scala
  app/models/project/ProjectSettings.scala
  app/models/project/Version.scala
  app/models/user/LoggedAction.scala
  app/models/user/Notification.scala
  app/models/user/Organization.scala
  app/models/user/User.scala
  app/models/user/role/OrganizationUserRole.scala
  app/models/user/role/ProjectUserRole.scala
  app/models/viewhelper/OrganizationData.scala
  app/models/viewhelper/ProjectData.scala
  app/models/viewhelper/ScopedProjectData.scala
  app/ore/organization/OrganizationMember.scala
  app/ore/organization/OrganizationOwned.scala
  app/ore/permission/role/GlobalUserRole.scala
  app/ore/permission/role/UserRole.scala
  app/ore/permission/scope/HasScope.scala
  app/ore/permission/scope/scope.scala
  app/ore/project/NotifyWatchersTask.scala
  app/ore/project/ProjectMember.scala
  app/ore/project/ProjectOwned.scala
  app/ore/project/factory/ProjectFactory.scala
  app/ore/project/io/PluginFile.scala
  app/ore/user/Member.scala
  app/ore/user/MembershipDossier.scala
  app/ore/user/UserOwned.scala
  app/util/syntax/package.scala
  build.sbt
Labels: status: ready for review

#695 Make it possible for a project to have no recommended version
  app/controllers/Users.scala
  app/controllers/project/Versions.scala
  app/db/impl/access/ProjectBase.scala
  app/models/project/Project.scala
  app/models/viewhelper/ProjectData.scala
  app/views/users/projects.scala.html
Labels: status: ready for review

#703 Cleanup config
  app/Bootstrap.scala
  app/controllers/ApiController.scala
  app/controllers/Application.scala
  app/controllers/Organizations.scala
  app/controllers/Users.scala
  app/controllers/project/Versions.scala
  app/controllers/sugar/Bakery.scala
  app/db/impl/access/OrganizationBase.scala
  app/db/impl/access/ProjectBase.scala
  app/db/impl/access/UserBase.scala
  app/db/impl/service/OreModelService.scala
  app/db/query/UserQueries.scala
  app/discourse/RecoveryTask.scala
  app/discourse/SpongeForums.scala
  app/form/project/TChannelData.scala
  app/mail/Mailer.scala
  app/models/project/Page.scala
  app/models/project/ProjectSettings.scala
  app/models/user/User.scala
  app/models/user/role/UserRoleModel.scala
  app/ore/OreConfig.scala
  app/ore/OreEnv.scala
  app/ore/project/ProjectTask.scala
  app/ore/project/factory/ProjectFactory.scala
  app/ore/rest/OreRestfulApi.scala
  app/ore/user/FakeUser.scala
  app/ore/user/MembershipDossier.scala
  app/security/spauth/SingleSignOnConsumer.scala
  app/security/spauth/SpongeAuthApi.scala
  app/util/StatusZ.scala
  app/views/bootstrap/header.scala.html
  app/views/bootstrap/layout.scala.html
  app/views/home.scala.html
  app/views/projects/channels/helper/modalManage.scala.html
  app/views/projects/channels/list.scala.html
  app/views/projects/create.scala.html
  app/views/projects/discuss.scala.html
  app/views/projects/pages/view.scala.html
  app/views/projects/settings.scala.html
  app/views/projects/versions/view.scala.html
  app/views/projects/view.scala.html
  app/views/users/admin/queue.scala.html
  app/views/users/admin/userAdmin.scala.html
  app/views/users/authors.scala.html
  app/views/users/projects.scala.html
  app/views/users/staff.scala.html
  app/views/users/view.scala.html
  conf/application.conf.template
Labels: requires: config update, status: ready for review

#705 Use json db field for json stuff
  .travis.yml
  app/controllers/Reviews.scala
  app/db/impl/OrePostgresDriver.scala
  app/db/impl/schema/tableSchema.scala
  app/db/query/DoobieOreProtocol.scala
  app/models/admin/Review.scala
  app/models/project/Project.scala
  build.sbt
  conf/evolutions/default/108.sql
Labels: status: ready for review

#709 Delete version assets
  app/db/impl/schema/tableSchema.scala
  app/models/project/Version.scala
  app/ore/project/factory/ProjectFactory.scala
  conf/evolutions/default/109.sql
  test/SchemaSpec.scala
Labels: status: ready for review

#706 Add review states to versions to replace isReviewed and isNonReviewed Resolves #698
  app/assets/stylesheets/_version-list.scss
  app/controllers/Application.scala
  app/controllers/Reviews.scala
  app/controllers/project/Versions.scala
  app/db/impl/OrePostgresDriver.scala
  app/db/impl/schema/tableSchema.scala
  app/db/query/DoobieOreProtocol.scala
  app/models/project/ReviewState.scala
  app/models/project/Version.scala
  app/models/user/LoggedAction.scala
  app/models/viewhelper/HeaderData.scala
  app/ore/rest/OreRestfulApi.scala
  app/views/projects/versions/unsafeDownload.scala.html
  app/views/projects/versions/view.scala.html
  app/views/users/admin/reviews.scala.html
  conf/evolutions/default/110.sql
  conf/messages
  conf/routes
  public/javascripts/review.js
  public/javascripts/versionList.js
  test/SchemaSpec.scala
Labels: component: review, status: ready for review

#713 Fix page creation
  app/controllers/project/Pages.scala
  app/models/project/Project.scala
  public/javascripts/pageEdit.js
Labels: status: ready for review

#710 Update doobie to 0.6
  app/db/impl/service/OreModelService.scala
  app/db/query/DoobieOreProtocol.scala
  build.sbt
  test/DbSpec.scala
Labels: status: ready for review
