Repository SpongePowered/Ore, pull requests merged in 2018-04, with the labels that each got.

#516 Add that non-home pages have a longer max length
  app/form/OreForms.scala
  app/models/project/Page.scala
  app/models/project/Project.scala
  conf/application.conf.template
Labels: requires: config update, status: ready for review

#518 Updated dependencies
  build.sbt
  project/plugins.sbt
Labels: status: ready for review

#519 Add undo approval button
  app/controllers/Reviews.scala
  app/db/impl/table/ModelKeys.scala
  app/models/admin/Review.scala
  app/models/project/Version.scala
  app/views/users/admin/reviews.scala.html
  conf/routes
  public/javascripts/review.js
Labels: component: frontend

#521 Added different messaging for versions in non-reviewed channels
  app/assets/stylesheets/main.scss
  app/controllers/project/Versions.scala
  app/ore/rest/OreWrites.scala
  app/views/projects/versions/list.scala.html
  app/views/projects/versions/unsafeDownload.scala.html
  conf/messages
  conf/routes
  public/javascripts/versionList.js
Labels: component: frontend

#471 Allow sending a changelog when using the deploy API endpoint
  app/controllers/ApiController.scala
  app/form/OreForms.scala
  app/form/project/VersionDeployForm.scala
Labels: component: api

#524 Fixed go back button
  app/views/linkout.scala.html
  app/views/projects/versions/unsafeDownload.scala.html
  public/javascripts/main.js
Labels: component: frontend
