Repository SpongePowered/Ore, pull requests merged in 2018-03, with the labels that each got.

#499 Update from Raven to Sentry
  build.sbt
  conf/logback.xml
  conf/sentry.properties
Labels: component: backend

#506 Rework of the plugin list
  app/assets/stylesheets/_user.scss
  app/assets/stylesheets/main.scss
  app/views/home.scala.html
  app/views/projects/list.scala.html
  app/views/utils/userAvatar.scala.html
  public/images/ore-colored.svg
Labels: component: frontend, priority: low

#511 Fix Role Clearing
  app/models/project/Project.scala
  app/models/user/Organization.scala
  app/ore/user/MembershipDossier.scala
Labels: status: ready for review

#503 Add Ore Developer Role (Closes #484)
  app/ore/permission/PermissionPredicate.scala
  app/ore/permission/role/RoleTypes.scala
Labels: component: backend, priority: high, status: ready for review

#514 Add modal to prompt for delete of version
  app/views/projects/versions/view.scala.html
  conf/messages
Labels: component: frontend, status: ready for review
