Repository SpongePowered/Ore, pull requests merged in 2018-10, with the labels that each got.

#673 Added pre-commit script
  README.md
  scripts/README.md
  scripts/pre-commit
Labels: status: ready for review

#675 Updated play-discourse to show more specific error messages
  build.sbt
Labels: status: ready to merge

#676 Added new sponsor
  app/assets/stylesheets/main.scss
  conf/application.conf.template
  public/images/sponsors/gameserverkings.png
Labels: requires: config update, status: ready for review

#682 Fixed moving topics when project visibility changes
  app/controllers/project/Projects.scala
Labels: status: ready for review

#677 Make MembershipDossier a typeclass
  app/controllers/Application.scala
  app/controllers/Organizations.scala
  app/controllers/project/Projects.scala
  app/db/impl/access/OrganizationBase.scala
  app/form/organization/OrganizationMembersUpdate.scala
  app/models/project/Project.scala
  app/models/project/ProjectSettings.scala
  app/models/user/Organization.scala
  app/models/viewhelper/OrganizationData.scala
  app/ore/Joinable.scala
  app/ore/organization/OrganizationMember.scala
  app/ore/project/ProjectMember.scala
  app/ore/project/factory/ProjectFactory.scala
  app/ore/user/Member.scala
  app/ore/user/MembershipDossier.scala
Labels: status: ready for review, type: enhancement

#679 Only run task on visible projects and add some more sentry stuff
  app/controllers/Application.scala
  app/db/impl/schema/tableSchema.scala
  app/discourse/OreDiscourseApi.scala
  app/discourse/RecoveryTask.scala
  conf/sentry.properties
Labels: status: ready for review

#686 Fix pages
  app/controllers/project/Projects.scala
  app/controllers/project/Versions.scala
  app/db/impl/schema/PageSchema.scala
  build.sbt
Labels: priority: high, status: ready for review

#678 Make having a scope a typeclass property
  app/controllers/sugar/Actions.scala
  app/controllers/sugar/Requests.scala
  app/models/project/Channel.scala
  app/models/project/Flag.scala
  app/models/project/Page.scala
  app/models/project/Project.scala
  app/models/project/Version.scala
  app/models/statistic/ProjectView.scala
  app/models/user/Organization.scala
  app/models/user/User.scala
  app/models/user/role/OrganizationRole.scala
  app/models/user/role/ProjectRole.scala
  app/models/viewhelper/UserData.scala
  app/ore/Joinable.scala
  app/ore/organization/OrganizationMember.scala
  app/ore/permission/PermissionPredicate.scala
  app/ore/permission/role/GlobalRole.scala
  app/ore/permission/role/Role.scala
  app/ore/permission/scope/GlobalScope.scala
  app/ore/permission/scope/HasScope.scala
  app/ore/permission/scope/OrganizationScope.scala
  app/ore/permission/scope/ProjectScope.scala
  app/ore/permission/scope/Scope.scala
  app/ore/permission/scope/ScopeSubject.scala
  app/ore/permission/scope/scope.scala
  app/ore/project/ProjectMember.scala
  app/ore/user/Member.scala
Labels: status: needs testing, status: ready for review

#688 Only update version if it's defined
  app/controllers/ApiController.scala
  app/db/ModelService.scala
  app/models/project/ProjectSettings.scala
Labels: status: needs testing, status: ready for review

#687 Fix upload when using organization as owner
  app/models/project/ProjectSettings.scala
  app/models/user/User.scala
Labels: status: ready for review
