Repository SpongePowered/Ore, pull requests merged in 2019-04, with the labels that each got.

#782 Better perms
  app/controllers/ApiController.scala
  app/controllers/Application.scala
  app/controllers/OreBaseController.scala
  app/controllers/Organizations.scala
  app/controllers/Reviews.scala
  app/controllers/Users.scala
  app/controllers/project/Channels.scala
  app/controllers/project/Pages.scala
  app/controllers/project/Projects.scala
  app/controllers/project/Versions.scala
  app/controllers/sugar/Actions.scala
  app/db/impl/OrePostgresDriver.scala
  app/db/impl/access/UserBase.scala
  app/db/impl/model/common/Hideable.scala
  app/db/impl/schema/DbRoleTable.scala
  app/db/query/DoobieOreProtocol.scala
  app/db/query/UserQueries.scala
  app/form/organization/OrganizationMembersUpdate.scala
  app/models/user/User.scala
  app/models/user/role/DbRole.scala
  app/models/viewhelper/HeaderData.scala
  app/models/viewhelper/JoinableData.scala
  app/models/viewhelper/OrganizationData.scala
  app/models/viewhelper/ProjectData.scala
  app/models/viewhelper/ScopedOrganizationData.scala
  app/models/viewhelper/ScopedProjectData.scala
  app/models/viewhelper/UserData.scala
  app/ore/organization/OrganizationMember.scala
  app/ore/permission/Permission.scala
  app/ore/permission/package.scala
  app/ore/permission/permissionPredicate.scala
  app/ore/permission/role/Trust.scala
  app/ore/permission/role/roles.scala
  app/ore/project/ProjectMember.scala
  app/ore/rest/OreRestfulApi.scala
  app/views/bootstrap/header.scala.html
  app/views/projects/pages/view.scala.html
  app/views/projects/settings.scala.html
  app/views/projects/versions/list.scala.html
  app/views/projects/versions/view.scala.html
  app/views/projects/view.scala.html
  app/views/users/invite/roleSelect.scala.html
  app/views/users/memberList.scala.html
  app/views/users/projects.scala.html
  app/views/users/view.scala.html
  build.sbt
  conf/evolutions/default/114.sql
  conf/evolutions/default/115.sql
  test/SchemaSpec.scala
Labels: status: ready for review

#783 Redo home_projects view for the API
  app/controllers/project/Projects.scala
  conf/application.conf.template
  conf/evolutions/default/116.sql
Labels: status: ready for review

#784 API V2
  .travis.yml
  README.md
  app/Bootstrap.scala
  app/Module.scala
  app/assets/stylesheets/_user.scss
  app/controllers/ApiController.scala
  app/controllers/ApiV1Controller.scala
  app/controllers/ApiV2Controller.scala
  app/controllers/Application.scala
  app/controllers/Users.scala
  app/controllers/project/Versions.scala
  app/controllers/sugar/CircePlayController.scala
  app/controllers/sugar/Requests.scala
  app/db/impl/OrePostgresDriver.scala
  app/db/impl/schema/ApiKeySessionTable.scala
  app/db/impl/schema/ApiKeyTable.scala
  app/db/query/APIV2Queries.scala
  app/db/query/DoobieOreProtocol.scala
  app/db/query/UserQueries.scala
  app/models/api/ApiKey.scala
  app/models/api/ApiSession.scala
  app/models/project/ReviewState.scala
  app/models/project/VersionTag.scala
  app/models/protocols/APIV2.scala
  app/models/querymodels/apiV2QueryModels.scala
  app/ore/Color.scala
  app/ore/OreConfig.scala
  app/ore/permission/NamedPermission.scala
  app/ore/permission/package.scala
  app/ore/permission/role/roles.scala
  app/ore/permission/scope/scope.scala
  app/ore/project/Category.scala
  app/ore/project/ProjectSortingStrategy.scala
  app/ore/project/factory/ProjectFactory.scala
  app/ore/rest/OreRestfulApiV1.scala
  app/ore/user/FakeUser.scala
  app/ore/user/UserTask.scala
  app/util/OreMDC.scala
  app/views/bootstrap/layout.scala.html
  app/views/projects/channels/list.scala.html
  app/views/projects/versions/list.scala.html
  app/views/projects/view.scala.html
  app/views/users/apiKeys.scala.html
  app/views/users/view.scala.html
  build.sbt
  conf/application.conf.template
  conf/evolutions/default/117.sql
  conf/logback.xml
  conf/messages
  conf/routes
  extra/apiV2.http
  public/javascripts/apiKeysManagement.js
  public/javascripts/main.js
  public/javascripts/versionList.js
  test/APIV2QueriesSpec.scala
  test/UserQueriesSpec.scala
Labels: requires: config update, requires: environment update, status: needs testing, status: ready for review

#787 Oops, we are in 2019 already
  app/views/bootstrap/footer.scala.html
Labels: component: frontend, status: ready for review

#786 Purge PGP from the Ore codebase
  app/Bootstrap.scala
  app/assets/stylesheets/_user.scss
  app/controllers/ApiV2Controller.scala
  app/controllers/Users.scala
  app/controllers/project/Versions.scala
  app/db/impl/schema/UserTable.scala
  app/db/impl/schema/VersionTable.scala
  app/db/query/DoobieOreProtocol.scala
  app/db/query/UserQueries.scala
  app/form/OreForms.scala
  app/form/PGPPublicKeySubmission.scala
  app/mail/EmailFactory.scala
  app/models/project/Version.scala
  app/models/user/LoggedAction.scala
  app/models/user/User.scala
  app/models/viewhelper/UserData.scala
  app/ore/OreConfig.scala
  app/ore/project/factory/PendingVersion.scala
  app/ore/project/factory/ProjectFactory.scala
  app/ore/project/io/DownloadType.scala
  app/ore/project/io/PluginFile.scala
  app/ore/project/io/PluginFileWithData.scala
  app/ore/project/io/PluginUpload.scala
  app/ore/rest/OreWrites.scala
  app/ore/user/Prompt.scala
  app/security/pgp/PGPPublicKeyInfo.scala
  app/security/pgp/PGPVerifier.scala
  app/views/projects/create.scala.html
  app/views/projects/versions/create.scala.html
  app/views/users/view.scala.html
  build.sbt
  conf/application.conf.template
  conf/evolutions/default/118.sql
  conf/logback.xml
  conf/messages
  conf/routes
  public/javascripts/pluginUpload.js
  public/javascripts/versionList.js
  test/SchemaSpec.scala
Labels: requires: config update, status: needs testing, status: ready for review

#788 Fix offsite linking and cleanup markdown rendering
  app/Module.scala
  app/controllers/Application.scala
  app/controllers/Reviews.scala
  app/controllers/project/Pages.scala
  app/controllers/project/Projects.scala
  app/controllers/project/Versions.scala
  app/models/admin/ProjectVisibilityChange.scala
  app/models/admin/Review.scala
  app/models/admin/VersionVisibilityChange.scala
  app/models/project/Page.scala
  app/models/project/Project.scala
  app/models/project/Version.scala
  app/models/viewhelper/ProjectData.scala
  app/ore/markdown/FlexmarkRenderer.scala
  app/ore/markdown/MarkdownRenderer.scala
  app/views/projects/admin/notes.scala.html
  app/views/projects/discuss.scala.html
  app/views/projects/pages/view.scala.html
  app/views/projects/settings.scala.html
  app/views/projects/stargazers.scala.html
  app/views/projects/versions/list.scala.html
  app/views/projects/versions/log.scala.html
  app/views/projects/versions/view.scala.html
  app/views/projects/view.scala.html
  app/views/users/admin/reviews.scala.html
  app/views/users/admin/visibility.scala.html
  build.sbt
Labels: status: needs testing, status: ready for review

#791 Remove huge javascript comments
  ore/public/javascripts/actionLog.js
  ore/public/javascripts/apiKeysManagement.js
  ore/public/javascripts/channelManage.js
  ore/public/javascripts/flags.js
  ore/public/javascripts/hideProject.js
  ore/public/javascripts/home.js
  ore/public/javascripts/iconUpload.js
  ore/public/javascripts/keyGen.js
  ore/public/javascripts/main.js
  ore/public/javascripts/memberList.js
  ore/public/javascripts/membersConfig.js
  ore/public/javascripts/notes.js
  ore/public/javascripts/notifications.js
  ore/public/javascripts/orgCreate.js
  ore/public/javascripts/orgInvites.js
  ore/public/javascripts/pageCollapse.js
  ore/public/javascripts/pageEdit.js
  ore/public/javascripts/pluginUpload.js
  ore/public/javascripts/projectCreateValidate.js
  ore/public/javascripts/projectDetail.js
  ore/public/javascripts/projectDiscuss.js
  ore/public/javascripts/projectManage.js
  ore/public/javascripts/queue.js
  ore/public/javascripts/review.js
  ore/public/javascripts/spongie.js
  ore/public/javascripts/stats.js
  ore/public/javascripts/userAdmin.js
  ore/public/javascripts/userList.js
  ore/public/javascripts/userPage.js
  ore/public/javascripts/userSearch.js
  ore/public/javascripts/versionCreateChannelNew.js
  ore/public/javascripts/versionList.js
Labels: status: ready for review

#793 Move category link generation away from javascript
  ore/app/assets/stylesheets/main.scss
  ore/app/views/bootstrap/header.scala.html
  ore/app/views/home.scala.html
  ore/public/javascripts/home.js
  ore/public/javascripts/main.js
Labels: status: ready to merge

#795 Fixed KEY_ENTER variable to be only defined once
  ore/public/javascripts/pageEdit.js
  ore/public/javascripts/userSearch.js
Labels: status: ready for review

#796 Added opengraph meta tags to the main page
  ore/app/views/home.scala.html
Labels: status: ready for review

#794 Splits off the Discourse code
  build.sbt
  discourse/src/main/scala/ore/discourse/AkkaDiscourseApi.scala
  discourse/src/main/scala/ore/discourse/DisabledDiscourseApi.scala
  discourse/src/main/scala/ore/discourse/DiscourseApi.scala
  discourse/src/main/scala/ore/discourse/DiscoursePost.scala
  ore/app/controllers/project/Pages.scala
  ore/app/controllers/project/Projects.scala
  ore/app/discourse/DiscourseApiF.scala
  ore/app/discourse/OreDiscourseApi.scala
  ore/app/discourse/RecoveryTask.scala
  ore/app/discourse/SpongeForums.scala
  ore/app/models/project/Page.scala
  ore/app/ore/OreConfig.scala
  ore/app/views/projects/discuss.scala.html
  ore/app/views/projects/invite.scala.html
  ore/conf/application.conf.template
  ore/conf/logback.xml
  scripts/pre-commit
Labels: status: needs testing, status: ready for review
