Repository SpongePowered/Ore, pull requests merged in 2019-01, with the labels that each got.

#726 Add stargazers [WIP]
  app/assets/stylesheets/_project.scss
  app/assets/stylesheets/main.scss
  app/controllers/project/Projects.scala
  app/ore/OreConfig.scala
  app/views/projects/pages/view.scala.html
  app/views/projects/stargazers.scala.html
  app/views/projects/view.scala.html
  conf/application.conf.template
  conf/routes
  public/javascripts/projectDetail.js
Labels: status: in progress

#724 Add proper MDC Resolves #215
  app/Bootstrap.scala
  app/controllers/ApiController.scala
  app/controllers/Users.scala
  app/controllers/project/Versions.scala
  app/controllers/sugar/Actions.scala
  app/controllers/sugar/Requests.scala
  app/db/impl/access/OrganizationBase.scala
  app/db/impl/access/ProjectBase.scala
  app/db/impl/access/UserBase.scala
  app/db/impl/service/OreModelService.scala
  app/discourse/DiscourseMDC.scala
  app/discourse/OreDiscourseApi.scala
  app/mail/Mailer.scala
  app/models/user/Organization.scala
  app/models/user/Session.scala
  app/models/user/User.scala
  app/models/viewhelper/HeaderData.scala
  app/ore/project/ProjectTask.scala
  app/ore/project/factory/ProjectFactory.scala
  app/security/pgp/PGPPublicKeyInfo.scala
  app/security/pgp/PGPVerifier.scala
  app/security/spauth/SingleSignOnConsumer.scala
  app/security/spauth/SpongeAuthApi.scala
  app/util/FileUtils.scala
  app/util/OreMDC.scala
  app/util/WSUtils.scala
  build.sbt
Labels: status: ready for review

#725 Misc fixes
  app/controllers/Application.scala
  app/controllers/Users.scala
  app/db/impl/access/ProjectBase.scala
  app/ore/project/ProjectTask.scala
  app/ore/project/factory/ProjectFactory.scala
  conf/messages
Labels: requires: config update, status: needs testing, status: ready for review

#727 Updated dependencies
  app/models/project/Page.scala
  build.sbt
  project/build.properties
  project/plugins.sbt
Labels: status: in progress

#733 Changes to the logback configuration
  conf/logback.xml
Labels: status: ready for review

#731 Some changes in the base layout
  app/ErrorHandler.scala
  app/assets/stylesheets/_project.scss
  app/assets/stylesheets/main.scss
  app/controllers/project/Versions.scala
  app/controllers/sugar/ActionHelpers.scala
  app/mail/EmailFactory.scala
  app/views/bootstrap/header.scala.html
  app/views/bootstrap/layout.scala.html
  app/views/createOrganization.scala.html
  app/views/errors/error.scala.html
  app/views/errors/notFound.scala.html
  app/views/errors/timeout.scala.html
  app/views/home.scala.html
  app/views/linkout.scala.html
  app/views/projects/admin/flags.scala.html
  app/views/projects/admin/notes.scala.html
  app/views/projects/channels/list.scala.html
  app/views/projects/create.scala.html
  app/views/projects/discuss.scala.html
  app/views/projects/helper/panelCreate.scala.html
  app/views/projects/invite.scala.html
  app/views/projects/log.scala.html
  app/views/projects/pages/view.scala.html
  app/views/projects/settings.scala.html
  app/views/projects/stargazers.scala.html
  app/views/projects/versions/create.scala.html
  app/views/projects/versions/list.scala.html
  app/views/projects/versions/log.scala.html
  app/views/projects/versions/unsafeDownload.scala.html
  app/views/projects/versions/view.scala.html
  app/views/projects/view.scala.html
  app/views/users/admin/activity.scala.html
  app/views/users/admin/flags.scala.html
  app/views/users/admin/health.scala.html
  app/views/users/admin/log.scala.html
  app/views/users/admin/queue.scala.html
  app/views/users/admin/reviews.scala.html
  app/views/users/admin/stats.scala.html
  app/views/users/admin/userAdmin.scala.html
  app/views/users/admin/visibility.scala.html
  app/views/users/authors.scala.html
  app/views/users/notifications.scala.html
  app/views/users/projects.scala.html
  app/views/users/staff.scala.html
  app/views/users/view.scala.html
  app/views/utils/alert.scala.html
  app/views/utils/email.scala.html
Labels: status: ready for review

#737 Fix some templates and display errors from auth correctly
  app/controllers/Organizations.scala
  app/db/impl/access/OrganizationBase.scala
  app/security/spauth/SpongeAuthApi.scala
  app/util/WSUtils.scala
  app/views/createOrganization.scala.html
  app/views/linkout.scala.html
  app/views/utils/alert.scala.html
Labels: status: auth pending, status: ready to merge

#739 add open graph protocol to plugin pages
  app/views/bootstrap/layout.scala.html
  app/views/projects/view.scala.html
Labels: status: ready for review
