Repository SpongePowered/Ore, pull requests merged in 2019-02, with the labels that each got.

#746 Update to play 2.7
  app/ErrorHandler.scala
  app/Module.scala
  app/controllers/Users.scala
  app/controllers/project/Projects.scala
  app/filters/MimeKeyedCspFilter.scala
  app/models/project/ProjectSettings.scala
  app/ore/OreConfig.scala
  app/ore/project/io/PluginFileWithData.scala
  app/ore/project/io/ProjectFiles.scala
  app/security/CryptoUtils.scala
  app/security/NonceFilter.scala
  app/util/StringUtils.scala
  app/views/bootstrap/layout.scala.html
  app/views/home.scala.html
  app/views/projects/admin/notes.scala.html
  app/views/projects/channels/list.scala.html
  app/views/projects/create.scala.html
  app/views/projects/discuss.scala.html
  app/views/projects/pages/modalPageCreate.scala.html
  app/views/projects/pages/view.scala.html
  app/views/projects/settings.scala.html
  app/views/projects/stargazers.scala.html
  app/views/projects/versions/create.scala.html
  app/views/projects/versions/list.scala.html
  app/views/projects/view.scala.html
  app/views/users/admin/queue.scala.html
  app/views/users/admin/reviews.scala.html
  app/views/users/admin/stats.scala.html
  app/views/users/authors.scala.html
  app/views/users/staff.scala.html
  app/views/users/view.scala.html
  build.sbt
  conf/application.conf.template
  conf/logback.xml
  project/plugins.sbt
Labels: requires: config update, status: needs testing, status: ready for review

#747 only show pgp modal with private info to authenticated users
  app/views/users/view.scala.html
Labels: status: ready for review

#748 Only show recommended version download button if there is one
  app/views/projects/view.scala.html
Labels: status: ready for review

#749 Send version description in API
  app/ore/rest/OreRestfulApi.scala
Labels: status: ready for review

#751 Try to fix stats stuff
  app/db/impl/DbUpdateTask.scala
  app/db/impl/access/ProjectBase.scala
  app/ore/StatTracker.scala
  app/util/IOUtils.scala
  conf/evolutions/default/113.sql
Labels: status: ready for review

#753 Fix unlisted not shown on user profile
  app/controllers/Users.scala
  app/db/query/UserQueries.scala
Labels: status: ready for review

#756 Fixes and updates
  app/assets/stylesheets/_user.scss
  app/views/projects/versions/view.scala.html
  app/views/users/admin/reviews.scala.html
  app/views/users/notifications.scala.html
  build.sbt
  public/javascripts/notifications.js
Labels: status: ready for review

#757 Hotfix: downgrade slick pg due to startup problems
  build.sbt
Labels: status: in progress

#760 Remove erroneous bracket in avatar URL
  app/views/bootstrap/header.scala.html
Labels: status: in progress

#759 Add link icon on hover to links on markdown headers
  app/assets/stylesheets/_editor.scss
  app/models/project/Page.scala
Labels: component: frontend, status: changes requested
