Repository SpongePowered/Ore, pull requests merged in 2019-07, with the labels that each got.

#836 Use vue for the homepage
  build.sbt
  ore/app/assets/stylesheets/main.scss
  ore/app/controllers/Application.scala
  ore/app/views/home.scala.html
  ore/app/views/projects/channels/helper/modalManage.scala.html
  ore/conf/routes
  ore/public/javascripts/home.js
  oreClient/.browserslistrc
  oreClient/postcss.config.js
  oreClient/src/main/resources/assets/Home.vue
  oreClient/src/main/resources/assets/components/Icon.vue
  oreClient/src/main/resources/assets/components/Pagination.vue
  oreClient/src/main/resources/assets/components/ProjectList.vue
  oreClient/src/main/resources/assets/components/Tag.vue
  oreClient/src/main/resources/assets/dummy.js
  oreClient/src/main/resources/assets/home.js
  oreClient/src/main/resources/assets/scss/_variables.scss
  oreClient/src/main/resources/assets/utils.js
  oreClient/webpack.config.common.js
  oreClient/webpack.config.dev.js
  oreClient/webpack.config.prod.js
  oreClient/yarn.lock
  orePlayCommon/app/controllers/sugar/Calls.scala
  orePlayCommon/app/views/layout/base.scala.html
  orePlayCommon/app/views/layout/header.scala.html
  project/plugins.sbt
Labels: status: ready for review

#848 Removed some sponsors
  ore/conf/application.conf.template
  ore/public/images/sponsors/enjin.png
  ore/public/images/sponsors/gameserverkings.png
Labels: status: ready for review

#849 Fixed evolutions
  ore/app/OreApplicationLoader.scala
Labels: status: ready for review

#850 Update dependencies
  build.sbt
  oreClient/yarn.lock
Labels: status: ready to merge

#851 Update webpack dev server
  build.sbt
Labels: status: in progress

#853 Updated a bundge of libraries
  build.sbt
  oreClient/yarn.lock
  project/plugins.sbt
Labels: status: ready to merge

#852 Cache yarn
  .travis.yml
Labels: status: ready to merge

#854 Update doobie
  apiV2/app/db/impl/query/APIV2Queries.scala
  build.sbt
  models/src/main/scala/ore/db/impl/query/DoobieOreProtocol.scala
  ore/app/db/impl/service/OreModelService.scala
  orePlayCommon/app/util/TaskUtils.scala
Labels: status: ready for review

#855 Only ship the font-awesome icons we use
  build.sbt
  ore/public/javascripts/keyGen.js
  ore/public/javascripts/pageCollapse.js
  ore/public/javascripts/projectCreateValidate.js
  ore/public/javascripts/userSearch.js
  oreClient/postcss.config.js
  oreClient/src/main/resources/assets/font-awesome.js
  oreClient/webpack.config.common.js
  oreClient/yarn.lock
  orePlayCommon/app/views/layout/base.scala.html
Labels: status: ready for review

#858 Changed exclude to include
  oreClient/webpack.config.common.js
Labels: status: in progress

#859 Fix font awesome stylesheet
  build.sbt
  oreClient/src/main/resources/assets/font-awesome.js
  oreClient/webpack.config.common.js
  oreClient/yarn.lock
  orePlayCommon/app/views/layout/base.scala.html
Labels: status: ready for review

#860 Show visibility in project list again
  oreClient/src/main/resources/assets/components/ProjectList.vue
  oreClient/src/main/resources/assets/font-awesome.js
  oreClient/src/main/resources/assets/home.js
Labels: status: ready for review

#861 Run webpack in production too
  build.sbt
Labels: status: ready to merge

#862 Misc cleanup and a test
  .scalafmt.conf
  apiV2/app/controllers/apiv2/ApiV2Controller.scala
  apiV2/app/db/impl/query/APIV2Queries.scala
  apiV2/app/models/querymodels/apiV2QueryModels.scala
  auth/src/main/scala/ore/auth/AkkaSSOApi.scala
  db/src/main/scala/ore/db/access/modelAssociationAccess.scala
  models/src/main/scala/ore/data/Platforms.scala
  models/src/main/scala/ore/data/project/Dependency.scala
  models/src/main/scala/ore/db/impl/schema/VersionTagTable.scala
  models/src/main/scala/ore/models/project/Version.scala
  models/src/main/scala/ore/models/project/VersionTag.scala
  ore/app/OreApplicationLoader.scala
  ore/app/controllers/Application.scala
  ore/app/controllers/project/Versions.scala
  ore/app/db/impl/service/OreModelService.scala
  ore/app/views/home.scala.html
  ore/app/views/projects/tag.scala.html
  ore/app/views/projects/versions/view.scala.html
  ore/app/views/projects/view.scala.html
  ore/app/views/swagger.scala.html
  ore/app/views/utils/userAvatar.scala.html
  ore/conf/application.conf.template
  ore/conf/evolutions/default/125.sql
  ore/conf/messages
  ore/public/errors/400.html
  ore/public/errors/404.html
  ore/public/errors/500.html
  ore/public/errors/502.html
  ore/test/db/APIV2QueriesSpec.scala
  ore/test/db/AppQueriesSpec.scala
  ore/test/db/DbSpec.scala
  ore/test/db/ModelServiceSpec.scala
  ore/test/db/SchemaSpec.scala
  ore/test/db/UserQueriesSpec.scala
  orePlayCommon/app/db/impl/query/WebDoobieOreProtocol.scala
  orePlayCommon/app/models/querymodels/ViewTag.scala
  orePlayCommon/app/ore/OreConfig.scala
  orePlayCommon/app/ore/models/project/factory/PendingVersion.scala
  orePlayCommon/app/ore/models/project/factory/ProjectFactory.scala
  orePlayCommon/app/ore/models/project/io/PluginFileData.scala
  orePlayCommon/app/util/TaskUtils.scala
  orePlayCommon/app/util/ZIOFileIO.scala
  orePlayCommon/app/views/errors/error.scala.html
  orePlayCommon/app/views/errors/notFound.scala.html
  orePlayCommon/app/views/errors/timeout.scala.html
  orePlayCommon/app/views/layout/base.scala.html
  orePlayCommon/app/views/layout/footer.scala.html
  orePlayCommon/app/views/layout/header.scala.html
Labels: status: ready for review

#863 Add timings tracking
  models/src/main/scala/ore/db/impl/query/DoobieOreProtocol.scala
  ore/app/OreApplicationLoader.scala
  ore/app/controllers/Application.scala
  ore/app/controllers/project/Projects.scala
  ore/app/filters/LoggingFilter.scala
  ore/conf/application.conf.template
  ore/conf/logback.xml
  orePlayCommon/app/ore/OreConfig.scala
Labels: status: ready for review
